### PR TITLE
Support emptying of dynamic variable pool via YAML.

### LINKED ISSUE #10: Empty the variable pool during a run via YAML
We create a big YAML file and want to delete the dynamic variable pool during execution. So we added the possibility to delete all variables via:

```yaml
Store : Delete 
```

#9 Related PR by m-31

### PR DESCRIPTION
**Pull request by m-31**
We create a big YAML file and want to delete the dynamic variable pool during execution. So we added the possibility to delete all variables via:

- Store : Delete

### CODE REVIEW

**Comment by rschwietzke** [comment]
Thank you very much. We will take a look.

**Comment by rschwietzke** [comment]
I took the freedom to change the implementation a little and to add some more test cases along the way. Thanks for the PR and happy testing. Let me know if this works for you as initially imagined.

**Comment by m-31** [comment]
Thank you very much!

Now we have some problems testing with a large YAML file with arrival rates. Because the arrival rates are related to transactions and the YAML file is so large, meeting the arrival rate does not work (user threads go high, the load on the computer is very high, etc.)

Maybe that was the wrong approach. Now we wrote a wrapper class for the large YAML file, with a method `synchronized String getSequence()`. This method delivers small (mutually independent!) sections of the YAML file (including a constant header). Now we patched `com.xceptance.xlt.nocoding.parser.yaml.YamlParser` and replaced in line 53
```        
        final Node root = yaml.compose(createReader(pathToFile));
```
by
```
        final Node root = yaml.compose(new StringReader(YamlProvider.getInstance("testdata/TDLoadtestAPI.yaml").getSequence()));
```
and voilà! **Everything worked as expected.**

This quick and dirty hack was only for a prove of concept - but for a general solution we need the possibility to assign a YAML structure dynamically to a test case. Some kind of configurable YAML provider. Or perhaps more generally a `List <Command>` provider.

Perhaps we should simply create our own version of `AbstractNocodingTestCase`...?

**Comment by rschwietzke** [comment]
The design calls for a YAML file per scenarios or user type. Hence later you can have 10 user doing logins and 5 orders and so on. Each of these types also gets its own arrival rate as well as user count. Please let us know if you have questions. We can also have a call to discuss that if you like. Seem to be a small conceptual misunderstanding but maybe on the other hand I don't get the idea of a large YAML file...

**Comment by m-31** [comment]
For several years we have had a load test in production that uses scenarios. This concept has certain drawbacks that we want to overcome. We are now implementing a new approach: replaying live traffic. Hence the large YAML file ...

**Comment by rschwietzke** [comment]
Replaying traffic is ok. But a large YAML file is a lot of data... shall we talk about that and maybe you can share a demo?

**Comment by m-31** [comment]
(via email)

**Pull request merged**
